name: puremvc
description: >
    PureMVC is a lightweight framework for creating applications based upon the classic
    Model-View-Controller design meta-pattern. It supports modular programming through
    the use of Multiton Core actors.
version: 2.0.4
author: Cliff Hall <cliff.hall@puremvc.org>
homepage: http://www.puremvc.org
dependencies:
  unittest: any
