name: puremvc
version: 2.0.5
author: Cliff Hall <cliff.hall@puremvc.org>
description: PureMVC is a lightweight framework for creating applications based upon the classic Model-View-Controller design meta-pattern. It supports modular programming through the use of Multiton Core actors.
homepage: http://www.puremvc.org
dependencies:
  browser: any
dev_dependencies:
  unittest: any
